### ISSUE TITLE
Burn explanation

### ISSUE THREAD

**Issue by ErgoWhale** [ThierryM1212/ergo-token-minter#3]
Hello,

I used the token burner today and I believe that it worked. The transaction can be found here: https://explorer.ergoplatform.com/en/transactions/d2557974ff28025579f509f868e1089d6f1e93b1e05806c1acdc295583317d77

Are you able to add an explanation to the docs of what happens when the coins are burnt? I think I understand that the coin goes in on an input, but it's not obvious that it doesn't exist anywhere in the output. I'm planning to mint a bunch of tokens and I'd like to really understand it to be able to explain to others.

Thank you for this tool!

**Comment by ThierryM1212** [comment]
Hello,
Ok, I've added a comment in the about page, coming the the EIP-4 token specification:
"Unlike ergs, other tokens can be burnt: the total amount for a token in transaction inputs should be no less than the amount of the outputs."

In order to mint and burn tokens you could rather use Safew wallet:
- There is a mint token page, also supporting pictures, audio and video NFT
- The send transaction page has a "burn mode" button to burn tokens
- There is no fee...

https://chrome.google.com/webstore/detail/safew-simple-and-fast-erg/fmpbldieijjehhalgjblbpgjmijencll
